options:
  substitution_option: 'ALLOW_LOOSE'
  env:
  - CLOUDSDK_COMPUTE_ZONE=us-central1-a
  - CLOUDSDK_CONTAINER_CLUSTER=gcore-kubeflow
  volumes:
  - name: go-modules
    path: /go
steps:
- name: 'gcr.io/cloud-builders/go:debian'
  args: ['build','-i','-o','api', 'cmd/api/main.go']
  env: ['PROJECT_ROOT=mad_demo']
- name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  #  - --tag=gcr.io/$PROJECT_ID/backend:$SHORT_SHA
  #  - --tag=gcr.io/$PROJECT_ID/backend:$TAG_NAME
  - --tag=gcr.io/$PROJECT_ID/api:staging
  - --tag=gcr.io/$PROJECT_ID/api:latest
  - .
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/api:staging"]

images:
#  - 'gcr.io/$PROJECT_ID/backend:$SHORT_SHA'
#  - 'gcr.io/$PROJECT_ID/backend:$TAG_NAME'
- 'gcr.io/$PROJECT_ID/api:latest'
timeout: 300s
tags: ['api']
