options:
  substitution_option: 'ALLOW_LOOSE'
  env:
    - CLOUDSDK_COMPUTE_ZONE=us-east4-a
    - CLOUDSDK_CONTAINER_CLUSTER=cbd-mad-demo
    - ENV=${_ENV}
  volumes:
    - name: k8s-module
      path: /k8s
steps:
  #  - name: gcr.io/$PROJECT_ID/skaffold:alpha
  #    args: ['build', '-f=grpc-server/skaffold.yaml']
  #    waitFor: ['-']
  #  - name: gcr.io/$PROJECT_ID/skaffold:alpha
  #    args: ['build', '-f=http-server/skaffold.yaml']
  #    waitFor: ['-']
  - id: 'render http'
    name: gcr.io/$PROJECT_ID/skaffold:alpha
    args: ['render', '-f=http-server/skaffold.yaml', '--output=k8s-http-server.yaml']
    waitFor: ['-']
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp','k8s-http-server.yaml','gs://mad-demo-k8s/']
    waitFor: ['render http']
  - id: 'render grpc'
    name: gcr.io/$PROJECT_ID/skaffold:alpha
    args: ['render', '-f=grpc-server/skaffold.yaml', '--output=k8s-grpc-server.yaml']
    waitFor: ['-']
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp','k8s-grpc-server.yaml','gs://mad-demo-k8s/']
    waitFor: ['render grpc']
#  - name: gcr.io/$PROJECT_ID/skaffold:alpha
#    args: ['deploy', '-f=https://raw.githubusercontent.com/ChrisGe4/mad-demo-config/master/skaffold-backend.yaml']
timeout: 400s
tags: ['backend-server']
