replicaCount: 1
env: dev

image:
  repository: gcr.io/gcore-dev01/rest-server
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8081
  targetPort: 8081

resources: {}

envVar:
  grpcServerHost: grpc-server
  grpcServerPort: 8090

