replicaCount: 1
env: dev

image:
  repository: gcr.io/cloud-build-delivery-mad/grpc-server
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8090
  targetPort: 8090

resources: {}


envVar:
  gcpProjectId: cloud-build-delivery-mad
  firestoreCollection: todo
